# Generated by Django 5.0.3 on 2024-06-12 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField(max_length=300)),
                ('summary', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, help_text='pdf file', null=True, upload_to='content_management_pdf', verbose_name='Content Pdf file')),
                ('categories', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Detail',
                'verbose_name_plural': 'Content Details',
                'db_table': 'content_item_table',
                'ordering': ['-created_at'],
            },
        ),
    ]
