# Generated by Django 5.0.3 on 2024-06-12 10:23

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permission_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, db_index=True, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, db_index=True, max_length=6, null=True)),
                ('is_auther', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_role', to='permission_app.rolemaster')),
            ],
            options={
                'verbose_name': 'User Detail',
                'verbose_name_plural': 'User Details',
                'db_table': 'user_details_table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalUserDetails',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('full_name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, db_index=True, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, db_index=True, max_length=6, null=True)),
                ('is_auther', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='permission_app.rolemaster')),
            ],
            options={
                'verbose_name': 'historical User Detail',
                'verbose_name_plural': 'historical User Details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
